name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd ~/restaurant-back
            git pull origin main
            make build
            R_ENV="${{ env.ENV }}" \
            R_JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            R_DEBUG="${{ env.DEBUG }}" \
            R_PPROF_ENABLED="${{ env.PPROF_ENABLED }}" \
            R_PG_DSN="${{ secrets.PG_DSN }}" \
            POSTGRES_USER="${{ env.POSTGRES_USER }}" \
            POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" docker compose up -d

